"""Hypercube feature distribution.

Features are arranged on a hypercube.
A data point is generated by picking a random point and activation magnitude;
nearby features activate with a profile controlled by a length-scale parameter.
"""

import torch
from torch import Tensor

from .base import Distribution


class HypercubeDistribution(Distribution):
    """Features arranged on a grid in [0, 1]^d with tent-bump activation.

    ``n_features`` points are placed on an evenly spaced grid in the unit
    hypercube.  To generate a sample we draw a random point **U** ~ Uniform([0, 1]^d)
    and magnitude *m*.  The feature at grid position **x** activates as

        x_φ = m · max(1 − ‖U − x‖ / ℓ, 0)

    where ‖·‖ is the L2 norm and ℓ is the length-scale.

    In 1-D this reduces to a triangle bump: features at 0, 1/(n−1), …, 1
    activate as ``max(1 − |U − x| / ℓ, 0)``.

    When ``n_features`` is a perfect ``cube_dim``-th power, a regular grid is
    used (e.g. 9 features on [0,1]² → 3x3 grid).  Otherwise features are placed
    at random positions sampled uniformly in [0, 1]^d.

    Args:
        n_features: Number of features. When not a perfect ``cube_dim``-th
            power, features are placed randomly instead of on a grid.
        length_scale: Controls the width of the tent bump.  Smaller values give
            sparser activations.
        cube_dim: Dimension of the hypercube (1 → interval, 2 → square, etc.).
        magnitude_range: ``(low, high)`` for the uniform magnitude distribution.
        **kwargs: Passed to ``Distribution`` (device, generator).
    """

    def __init__(
        self,
        n_features: int,
        length_scale: float = 0.5,
        cube_dim: int = 1,
        magnitude_range: tuple[float, float] = (0.9, 1.0),
        **kwargs,
    ):
        super().__init__(n_features, **kwargs)
        self.length_scale = length_scale
        self.cube_dim = cube_dim
        self.magnitude_range = magnitude_range

        # Check whether a regular grid is possible
        k = round(n_features ** (1.0 / cube_dim))
        self.grid_size: int | None = k if k**cube_dim == n_features else None

        # Place features on the grid: (n_features, cube_dim) in [0, 1]
        self.feature_positions = self._place_features()

    def _place_features(self) -> Tensor:
        """Place features on an evenly spaced grid in [0, 1]^d, or randomly if no grid fits."""
        if self.grid_size is None:
            return self._rand(self.n_features, self.cube_dim)

        if self.grid_size == 1:
            coords = torch.tensor([0.5], device=self.device)
        else:
            coords = torch.linspace(0, 1, self.grid_size, device=self.device)

        if self.cube_dim == 1:
            return coords.unsqueeze(-1)

        grids = [coords] * self.cube_dim
        mesh = torch.meshgrid(*grids, indexing="ij")
        return torch.stack([m.reshape(-1) for m in mesh], dim=-1)

    def sample(self, batch_size: int) -> Tensor:
        # Random point in [0, 1]^d: (batch, cube_dim)
        u = self._rand(batch_size, self.cube_dim)

        # L2 distance to each feature: (batch, n_features)
        dist = torch.cdist(u, self.feature_positions).squeeze(-1)

        # Tent bump: max(1 - dist / length_scale, 0)
        activation = (1 - dist / self.length_scale).clamp(min=0.0)

        # Random magnitude: (batch, 1)
        lo, hi = self.magnitude_range
        m = lo + (hi - lo) * self._rand(batch_size, 1)

        return m * activation
