"""Spherical feature distribution.

Features are arranged on a sphere (or circle in 1-D).
A data point is generated by picking a random point and activation magnitude;
nearby features activate with a profile controlled by a length-scale parameter.
"""

import math

import torch
from torch import Tensor

from .base import Distribution


class SphericalDistribution(Distribution):
    """Features arranged on a sphere with cosine-bump activation.

    ``n_features`` points are placed on a ``manifold_dim``-dimensional unit sphere with approximately equal spacing.  To generate a sample we draw a random direction **θ** and magnitude *m*.  The feature at position **v_φ** activates as

        x_φ = m · cos(α / ℓ)   if α / ℓ ≤ π/2,  else 0

    where α = arccos(v_φ · v_θ) is the geodesic distance and ℓ is the
    length-scale.

    Args:
        n_features: Number of features (points on the sphere).
        length_scale: Controls the width of the cosine bump.  Smaller values give sparser activations.
        manifold_dim: Dimension of the sphere the features live on.
            ``1`` → circle (S¹), ``2`` → ordinary sphere (S²), etc.
        magnitude_range: ``(low, high)`` for the uniform magnitude distribution.
        **kwargs: Passed to ``Distribution`` (device, generator).
    """

    def __init__(
        self,
        n_features: int,
        length_scale: float = 1.0,
        manifold_dim: int = 1,
        magnitude_range: tuple[float, float] = (0.9, 1.0),
        **kwargs,
    ):
        super().__init__(n_features, **kwargs)
        self.length_scale = length_scale
        self.manifold_dim = manifold_dim
        self.magnitude_range = magnitude_range

        # Place features on the sphere
        self.feature_positions = (
            self._place_features()
        )  # (n_features, manifold_dim + 1)

    def _place_features(self) -> Tensor:
        """Place ``n_features`` points approximately uniformly on S^{manifold_dim}."""
        if self.manifold_dim == 1:
            return self._place_on_circle()
        elif self.manifold_dim == 2:
            return self._place_on_sphere_fibonacci()
        else:
            return self._place_on_sphere_random()

    def _place_on_circle(self) -> Tensor:
        """Equal angular spacing on S¹."""
        angles = torch.linspace(
            0, 2 * math.pi, self.n_features + 1, device=self.device
        )[:-1]
        return torch.stack([torch.cos(angles), torch.sin(angles)], dim=-1)

    def _place_on_sphere_fibonacci(self) -> Tensor:
        """Fibonacci-lattice points on S² (approximately uniform)."""
        n = self.n_features
        golden = (1 + math.sqrt(5)) / 2
        i = torch.arange(n, device=self.device, dtype=torch.float)
        theta = torch.acos(1 - 2 * (i + 0.5) / n)
        phi = 2 * math.pi * i / golden
        return torch.stack(
            [
                torch.sin(theta) * torch.cos(phi),
                torch.sin(theta) * torch.sin(phi),
                torch.cos(theta),
            ],
            dim=-1,
        )

    def _place_on_sphere_random(self) -> Tensor:
        """Random points on S^{manifold_dim} via normalized Gaussians."""
        d = self.manifold_dim + 1
        pts = self._randn(self.n_features, d)
        return pts / pts.norm(dim=-1, keepdim=True)

    def _sample_direction(self, batch_size: int) -> Tensor:
        """Sample a uniformly random direction on S^{manifold_dim}."""
        d = self.manifold_dim + 1
        v = self._randn(batch_size, d)
        return v / v.norm(dim=-1, keepdim=True)

    def sample(self, batch_size: int) -> Tensor:
        # Random direction: (batch, d)
        direction = self._sample_direction(batch_size)

        # Dot product with all feature positions: (batch, n_features)
        # Clamp to [-1, 1] for numerical safety in arccos
        dots = (direction @ self.feature_positions.T).clamp(-1.0, 1.0)

        # Geodesic angle: (batch, n_features)
        alpha = torch.acos(dots)

        # Cosine bump with length-scale
        scaled = alpha / self.length_scale
        activation = torch.cos(scaled)
        activation = torch.where(scaled <= math.pi / 2, activation, 0.0)

        # Random magnitude: (batch, 1)
        lo, hi = self.magnitude_range
        m = lo + (hi - lo) * self._rand(batch_size, 1)

        return m * activation
