"""Toric feature distribution.

Features are arranged on a torus.
A data point is generated by picking a random point and activation magnitude;
nearby features activate with a profile controlled by a length-scale parameter.
"""

import math

import torch
from torch import Tensor

from .base import Distribution


class ToricDistribution(Distribution):
    """Features arranged on a flat torus T^d = S¹ × … × S¹ with cosine-bump activation.

    ``n_features`` points are placed at random angles on the ``toric_dim``-dimensional
    torus.  To generate a sample we draw a random point **θ** ∈ [0, 2π)^d and
    magnitude *m*.  The feature at angular position **φ** activates as

        x_φ = m · cos(d(θ, φ) / ℓ)   if d(θ, φ) / ℓ ≤ π/2,  else 0

    where d(θ, φ) is the geodesic (flat-torus) distance and ℓ is the length-scale.

    Args:
        n_features: Number of features, placed at uniformly random angles on T^d.
        length_scale: Controls the width of the cosine bump. Smaller values
            give sparser activations.
        toric_dim: Number of circular factors (1 → circle, 2 → T², etc.).
        magnitude_range: ``(low, high)`` for the uniform magnitude distribution.
        **kwargs: Passed to ``Distribution`` (device, generator).
    """

    def __init__(
        self,
        n_features: int,
        length_scale: float = 1.0,
        toric_dim: int = 1,
        magnitude_range: tuple[float, float] = (0.9, 1.0),
        **kwargs,
    ):
        super().__init__(n_features, **kwargs)
        self.length_scale = length_scale
        self.toric_dim = toric_dim
        self.magnitude_range = magnitude_range

        # Place features on the torus: (n_features, toric_dim) angles in [0, 2π)
        self.feature_angles = self._place_features()

    def _place_features(self) -> Tensor:
        """Place features at uniformly random angles on T^d."""
        return 2 * math.pi * self._rand(self.n_features, self.toric_dim)

    def _toric_distance(self, a: Tensor, b: Tensor) -> Tensor:
        """Geodesic distance on the flat torus.

        Args:
            a: (..., toric_dim) angles in [0, 2π).
            b: (..., toric_dim) angles in [0, 2π).

        Returns:
            (...) L2 norm of wrapped angular differences.
        """
        diff = (a - b).abs()
        wrapped = torch.minimum(diff, 2 * math.pi - diff)
        return wrapped.norm(dim=-1)

    def sample(self, batch_size: int) -> Tensor:
        # Random point on T^d: (batch, toric_dim)
        theta = 2 * math.pi * self._rand(batch_size, self.toric_dim)

        # Distance to each feature: (batch, n_features)
        # theta: (batch, 1, d), feature_angles: (n_features, d)
        dist = self._toric_distance(
            theta.unsqueeze(1), self.feature_angles.unsqueeze(0)
        )

        # Cosine bump with length-scale
        scaled = dist / self.length_scale
        activation = torch.cos(scaled)
        activation = torch.where(scaled <= math.pi / 2, activation, 0.0)

        # Random magnitude: (batch, 1)
        lo, hi = self.magnitude_range
        m = lo + (hi - lo) * self._rand(batch_size, 1)

        return m * activation
